<?php $title = 'Login'; ?>
<div class="container d-flex justify-content-center align-items-center min-vh-100">
    <div class="card shadow p-4 my-4" style="width: 100%; max-width: 400px;">
        <h4 class="card-title text-center mb-4">Login</h4>
        <form method="POST" action="">
            <?php if (isset($_SESSION['flash']['error'])): ?>
                <div class="alert alert-danger">
                    <?= $_SESSION['flash']['error']; ?>
                    <?php unset($_SESSION['flash']['error']); ?>
                </div>
            <?php endif; ?>
            <?php if (isset($_SESSION['flash']['success'])): ?>
                <div class="alert alert-success">
                    <?= $_SESSION['flash']['success']; ?>
                    <?php unset($_SESSION['flash']['success']); ?>
                </div>
            <?php endif; ?>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="text" name="email" class="form-control" id="email" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" name="password" class="form-control" id="password" required>
            </div>
            <div class="mb-3">
                <p class="text-dark">Doesn't have an account? <a href="<?= BASE_URL ?>signup.php">Signup now</a></p>
            </div>
            <button type="submit" class="btn btn-primary w-100">Login</button>
        </form>
    </div>
</div>